name: Generate Snake
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: leticiaafaleiros
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
