name: Generate Snake
on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:         

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: leticiaafaleiros
          svg_out_path: snake.svg

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: snake.svg

      - name: Deploy
        uses: actions/deploy-pages@v3
