name: Generate Snake
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      - uses: actions/checkout@v4
     
      - uses: Platane/snk@master
        id: snake
        with:
          github_user_name: leticiaafaleiros  
          svg_out_path: snake.svg 

     
      - name: Push to Output Branch
        uses: actions-js/push@v1
        with:
          branch: output
          directory: .
          files: snake.svg
          force: true  
