name: Generate Snake
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Animated Snake
        uses: Platane/snk@master
        with:
          github_user_name: leticiaafaleiros
          svg_out_path: snake.svg
          gif_out_path: snake.gif  # Adicionando saída GIF
          animate: true  # Força animação
          colors:
            background: '#0d1117'
            snake: '#58a6ff'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: |
            snake.svg
            snake.gif
